import {userBuilder} from '../support/generate'

describe('Register', () => {
    it('tests visual regression', () => {
        cy.visit('/signup')
        cy.matchImageSnapshot('signup')
    })

    it('register a new user', () => {
        const user = userBuilder()
        console.log(user)
        cy.visit('/signup')
            .get('[type="email"]')
            .type(user.email)
            .get('[placeholder="PASSWORD"]')
            .type(user.password)
            .get('[placeholder="REPEAT PASSWORD"]')
            .type(user.password)
            .get('[type="submit"]')
            .click()
            .wait(1000)
            .url()
            .should('eq', `${Cypress.config().baseUrl}/`)
    })

    it('tries to register an already taken email', () => {
        const user = userBuilder()
        console.log(user)
        cy.visit('/signup')
            .get('[type="email"]')
            .type('testuser@imyme.com')
            .get('[placeholder="PASSWORD"]')
            .type('123456')
            .get('[placeholder="REPEAT PASSWORD"]')
            .type('123456')
            .get('[type="submit"]')
            .click()
            .wait(1000)
            .url()
            .should('eq', `${Cypress.config().baseUrl}/signup`)
    })

    it('tries to register when password confirmation does not match', () => {
        const user = userBuilder()
        console.log(user)
        cy.visit('/signup')
            .get('[type="email"]')
            .type('testuser@imyme.com')
            .get('[placeholder="PASSWORD"]')
            .type('123456')
            .get('[placeholder="REPEAT PASSWORD"]')
            .type('654321')
            .get('[type="submit"]')
            .click()
            .wait(1000)
            .url()
            .should('eq', `${Cypress.config().baseUrl}/signup`)
    })
})
